### PR TITLE
Remove reverse lookups

### PR DESCRIPTION
**Pull request by cxkoda**
This PR heavily restructures the library code and adds some optimizations.

`auth` address reverse lookups do not have to be performed on the contract level. Instead, the subdomain label can be supplied externally, which allows us only rely on ENS resolutions and thus to remove a large chunk of inefficient code. 

`testValidate` now takes about 36k gas to execute.

Also I've added more verbose error messages.

### CODE REVIEW

**Comment by cxkoda** [comment]
I have seen in your other commit that you prefer `abstract contract LinkedAddress` over `library LinkedAddress`. Is there a specific reason for this?

**Comment by wwhchung** [comment]
Actually, I don't believe this is safe.  This works IF we can trust the input data and we rely on something like EIP-1271.  But, in isolation, we can't trust the input data and need to do the reverse lookup to confirm the actual domains match, right?  Otherwise I could access any main account.

**Comment by wwhchung** [comment]
And no, I can change to a library.  That's perfectly fine.

**Comment by cxkoda** [comment]
Isn't the only thing that counts that `auth.wallet.eth` correctly resolves to the address that tries to authenticate for `wallet.eth`? So it doesn't really matter if the reverse is even set for `authAddress`, imo.

**Comment by cxkoda** [comment]
The reverse record is only important for the application flow / UX. But not for the security of the protocol as far as I have understood.

**Comment by wwhchung** [comment]
Oh, I see, ya, clever!

**Comment by wwhchung** [comment]
I'm going to merge and add a unit test

**Comment by cxkoda** [comment]
ahhh no wait. I think you are absolutely right!

**Comment by cxkoda** [comment]
argh too late

**Comment by cxkoda** [comment]
The reverse lookup for `authAddress` is more or less irrelevant but the one for `mainAddress` isn't. This is the only thing that proves that the owner of `mainAddress` was also the one to set the ENS records. 

If we don't do the reverse lookup for the `mainAddress` I could e.g. create `hijacker.eth` that resolves to `wilkins.eth` and `auth.hijacker.eth` that resolves to one of my wallets. so using my `authAddress`, I could authenticate for  `hijacker.eth` which is actually `wilkins.eth`.

**Comment by wwhchung** [comment]
yes, that's it, let me write a unit test and add back the reverse lookup for mainAddress code.

**Comment by wwhchung** [comment]
Ok, just committed the fix and a test for the hijacker case.

**Pull request merged**
